### ISSUE TITLE
project 1 - Review my app

### ISSUE THREAD

**Issue by pureyang** [pureyang/dropbox#1]
Please review /cc @codepathreview

**Comment by timothy1ee** [comment]
This is for the iOS class @ Walmart starting next week, right? Can you fill out your contact information here, so we can add you to the roster: https://www.surveymonkey.com/r/ZT5H7WG

**Comment by pureyang** [comment]
hey tim, does this submission work for the iOS course for Product/UX as well?

**Comment by timothy1ee** [comment]
Yes, that's fine.
